import argparse
import math
import os
import random
import torch

from typing import Optional

from config import load_config
from utils import gen_cartesian_prod, load_yaml, refresh_directory


# Approximately low-rank covariance is generated by
#   (1) Generating a low-rank PSD matrix LL^T
#   (2) Generating a small PSD low-rank noise matrix \sigma Q \Lambda Q^T
#   (3) Summing the matrices in (1) and (2)



def gen_upper_triangular_indices(n, p, batch_size, seed=None):
    """
    Yields unique uppper upper-triangular (i, j) index pairs (0 ≤ i ≤ j < n),
    each with probability p, in batches of size batch_size.
    """
    if seed is not None:
        torch.manual_seed(seed)

    rows = torch.arange(n, dtype=torch.int32)
    leftover = None
    for points in gen_cartesian_prod(rows):

        points = points[points[:, 0] <= points[:, 1]]  # keep only upper triangular indices
        points = points[torch.rand(len(points)) < p]  # select indices with probabilty p
        
        leftover = points if leftover is None else torch.cat((leftover, points))
        while len(leftover) >= batch_size:
            yield leftover[:batch_size]
            leftover = leftover[batch_size:]
    if leftover is not None and len(leftover) > 0:
        yield leftover


def get_psd_noise_eig(
    n_vars: int, 
    rank: int, 
    scale: float,
    seed: Optional[int] = None
):

    if seed is not None:
        torch.manual_seed(seed)

    # Generate a random orthogonal matrix
    evecs, _ = torch.linalg.qr(torch.randn(n_vars, rank))

    # Generate nonnegative eigenvalues
    evals = scale * torch.abs(torch.randn(rank))

    return evecs, evals


def gen_approx_low_rank_cov(
    n_vars: int, 
    p_obs: int,
    rank: int, 
    noise_rank: int, 
    noise_scale: float, 
    batch_size: Optional[int] = None,
    seed: Optional[int] = None
):

    if seed is not None:
        torch.manual_seed(seed)

    # Generate loadings and noise eigenpairs
    loads = torch.randn(n_vars, rank)
    evecs, evals = get_psd_noise_eig(n_vars, noise_rank, noise_scale, seed)

    # Yield covariance in batches
    for points_batch in gen_upper_triangular_indices(n_vars, p_obs, batch_size, seed):
        
        loads_i = loads[points_batch[:,0]]  # shape: [batch_size, rank]
        loads_j = loads[points_batch[:,1]]  # shape: [batch_size, rank]
        evecs_i = evecs[points_batch[:,0]]  # shape: [batch_size, noise_rank]
        evecs_j = evecs[points_batch[:,1]]  # shape: [batch_size, noise_rank]

        # Batch of --> loads @ loads.t() + evecs @ torch.diag(evals) @ evecs.t()
        tmp1 = (loads_i * loads_j).sum(dim=1)           # shape: [batch_size]
        tmp2 = (evecs_i * evals * evecs_j).sum(dim=1)   # shape: [batch_size]
        cov_batch = tmp1 + tmp2

        yield points_batch, cov_batch
    


if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('--config', type=str)
    parser.add_argument('--design', type=str)
    parser.add_argument('--batch_size', type=int)
    parser.add_argument('--seed', type=int, default=12345)
    args = parser.parse_args()

    config = load_config(args.config)

    # Load design
    path_design = os.path.join(config.group_root, 'designs-lrcmc', f'{args.design}.yml')
    design = load_yaml(path_design)

    # Set paths
    dir_cov = os.path.join(config.group_root, 'out-lrcmc', args.design, 'cov')
    refresh_directory(dir_cov)
    path_points = lambda i: os.path.join(dir_cov, f'points_i-{i}_.pt')
    path_cov = lambda i: os.path.join(dir_cov, f'cov_split-full_i-{i}_.pt')

    # Write observed indices/covariance to disk in batches
    batch = 0
    for points_batch, cov_batch in gen_approx_low_rank_cov(
        design['n_vars'], 
        design['p_obs'], 
        design['rank'], 
        design['noise_rank'], 
        design['noise_scale'], 
        args.batch_size, 
        args.seed
    ):
        torch.save(points_batch, path_points(batch))
        torch.save(cov_batch, path_cov(batch))
        batch += 1
        




