import argparse
import nibabel as nib
import numpy as np
import os
import torch

from config import load_config
from utils import read_tensors


# NOTE: This script is to be run after compute_covariance.py as it needs
# the data folds generated by that file.

if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('--config', type=str)
    parser.add_argument('--dir_out_scratch', type=str)
    parser.add_argument('--sz_space', type=int, nargs='+')
    parser.add_argument('--n_sub', type=int)
    args = parser.parse_args()

    config = load_config(args.config)

    n_dim = len(args.sz_space)
    if n_dim not in [2, 3]:
        raise Exception("Script only supports 2- or 3-D spatial data!")

    # Directory prep
    dir_data = os.path.join(args.dir_out_scratch, 'data')
    dir_data_ica = os.path.join(args.dir_out_scratch, 'data-ica')
    os.makedirs(dir_data_ica, exist_ok=True)

    # Create NIFTI file for each subject
    for n in range(args.n_sub):

        data = read_tensors( # (J,M) --> (M1,M2,1,J) or (M1,M2,M3,J)
            dir_data,
            f'data-time_split-full_n-{n}_',
            sort_by=('i', int)
        )
        data = data.reshape(data.shape[0], *args.sz_space)
        if n_dim == 2: 
            data = torch.permute(data, (1, 2, 0)).unsqueeze(2)
        else: 
            data = torch.permute(data, (1, 2, 3, 0))
        data = nib.Nifti1Image(data.numpy(), np.eye(4))
        path = os.path.join(dir_data_ica, f'data_split-full_n-{n}.nii.gz')
        nib.save(data, path)



    # for split in ['full', 'train', 'valid']:
    #     for n in range(args.n_sub):

    #         data = read_tensors( # (J,M) --> (M1,M2,1,J)
    #             dir_data,
    #             f'data-time_split-{split}_n-{n}',
    #             sort_by=('i', int)
    #         )
    #         data = data.reshape(data.shape[0], *args.sz_space)
    #         data = torch.permute(data, (1, 2, 0)).unsqueeze(2)
    #         data = nib.Nifti1Image(data.numpy(), np.eye(4))
    #         path = os.path.join(dir_data_ica, f'data_split-{split}_n-{n}.nii.gz')
    #         nib.save(data, path)
