import argparse
import numpy as np
import os
import sys
import torch

from utils import (
    compute_loss, 
    execute_script, 
    load_config,
    model_from_loads, 
    multiply_list,
)


SIGMAS = [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]


if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('--config', type=str)
    parser.add_argument('--dir_out', type=str)
    parser.add_argument('--dir_out_scratch', type=str)
    parser.add_argument('--n_folds', type=int)
    parser.add_argument('--n_comps', type=int)
    parser.add_argument('--fixed_norm', type=float)
    args = parser.parse_args()

    config = load_config(args.config)

    # Directory/path preparation
    dir_data = os.path.join(args.dir_out_scratch, 'data')
    dir_cov = os.path.join(args.dir_out_scratch, 'cov')
    path_sigma = os.path.join(args.dir_out, f'sigma.pt')
    path_fold = lambda v: os.path.join(dir_data, f'subs_v-{v}.pt')  # NOTE: generated by compute_covariance.py
    path_out_space = lambda v: os.path.join(args.dir_out, f'icas-space_split-train_v-{v}.npy')
    path_out_time = lambda v: os.path.join(args.dir_out, f'icas-time_split-train_v-{v}.npy')

    # Build path/flags
    path = os.path.join(config.root, 'scripts', 'melodic_estimation.py')
    flags = {
        'config': args.config,
        'dir_out': args.dir_out,
        'dir_out_scratch': args.dir_out_scratch,
        'n_folds': args.n_folds,
        'n_comps': args.n_comps
    }

    # Run MELODIC for various sigmas
    best_sigma = None
    best_valid_loss = float('inf')
    for sigma in SIGMAS:
        flags['sigma'] = sigma

        valid_loss = 0
        for v in range(args.n_folds):

            # Run MELODIC
            flags['fold'] = v
            code = execute_script(path, flags, False)

            # Handle MELODIC error
            if code != 0: 
                sys.exit(1)

            # Compute validation loss
            loads = np.load(path_out_space(v))
            loads /= np.linalg.norm(loads)
            loads *= args.fixed_norm
            loads = loads.reshape(multiply_list(loads.shape[:3]), loads.shape[3])
            model = model_from_loads(torch.tensor(loads))
            valid_loss += compute_loss(model, dir_cov, 'valid', v).item()

        valid_loss /= args.n_folds
        print(f"sigma = {sigma} | valid_loss = {valid_loss}")

        # Break from loop if improvement stops or update best model
        if valid_loss > best_valid_loss:
            break
        best_valid_loss = valid_loss
        best_sigma = sigma

    # Save best sigma
    torch.save(torch.tensor(best_sigma, dtype=torch.float32), path_sigma)

    # Cleanup models
    for v in range(args.n_folds):
        if os.path.exists(path_out_space(v)):
            os.remove(path_out_space(v))
        if os.path.exists(path_out_time(v)):
            os.remove(path_out_time(v))


